### ISSUE TITLE
minor: use kitab font

### ISSUE THREAD

**Issue by mustafa0x** [AhmedElTabarani/hadith-checker-extension#12]
```css
@font-face {
  font-family: Kitab;
  src: url(https://fonts.nuqayah.com/kitab-base.woff2?v3);
  unicode-range: U+200?, U+60C, U+618-61B, U+61F, U+621-63A, U+640-655, U+65C, U+660-66C, U+670-671, U+6CC, U+6D4, U+6D6-6ED, U+8F0-8F3, U+FD3E-FD3F;
}
@font-face {
  font-family: Kitab;
  src: url(https://fonts.nuqayah.com/kitab-base-b.woff2?v3);
  font-weight: 700;
  unicode-range: U+200?, U+60C, U+618-61B, U+61F, U+621-63A, U+640-655, U+65C, U+660-66C, U+670-671, U+6CC, U+6D4, U+6D6-6ED, U+8F0-8F3, U+FD3E-FD3F;
}
@font-face {
  font-family: Kitab;
  src: url(https://fonts.nuqayah.com/kitab-phrases.woff2?v3);
  unicode-range:  U+E100-E103, U+FD3E-FD45, U+FD47-FD4F, U+FDF2, U+FDFA-FDFB, U+FDFD-FDFF;
}
@font-face {
  font-family: Kitab;
  src: url(https://fonts.nuqayah.com/kitab-phrases.woff2?v3);
  font-weight: 700;
  unicode-range:  U+E100-E103, U+FD3E-FD45, U+FD47-FD4F, U+FDF2, U+FDFA-FDFB, U+FDFD-FDFF;
}
body {
  font-family: Kitab,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue;
}
```

Also, it might be better UX to make this extension a link to `dorar.net/hadith?q=...` or `sunnah.one/?s=...`. Unless you need full control of course.
